# Change these first
owner: interoperable # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
sites:
  - name: Google
    url: https://www.google.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true
  - name: Gravatar.com
    url: gravatar.com/valiantly040d60ddad
  - name: LinkedIn Profile
    url: www.linkedin.com/in/peterpouliot
  - name: Cloudflare
    url: https://cloudflare.com
  - name: DockerHub
    url: https://hub.docker.com/orgs/interoperable/repositories
  - name: Unifi Cloud UI
    url: https://unifi.ui.com
  - name: GitHub-Pages URL
    url: https://interoperable.github.io
  - name: PPouliot GitHub Pages URL
    url: https://ppouliot.github.io
  - name: GitLab-Pages URL
    url: https://interoperable.gitlab.io
  - name: interoperable.systems
    url: https://interoperable.systems
  - name: upptime.interoperable.systems
    url: https://upptime.interoperable.systems
    
  - name: Synology Diskstation Adiminstration CLI Guide PDF
    url: https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_DiskStation_Administration_CLI_Guide.pdf
assignees:
 - ppouliot
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.interoperable.systems
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
